### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by Vaults1** [LegoCraftPE/iOS_LCPE-App#1]
1. Thank You!
2. How do you plan to host the app profile download page? I can host it on my site if you want.

**Comment by applqpak** [comment]
1. No worries.
2. If you could that would be so great. Once I create the Mobile Config / Profile I'll upload it on my Dropbox and you can just drop it on your site. Thanks!

**Comment by applqpak** [comment]
Actually, I'll make it now.

**Comment by k3ithos** [comment]
You should do the same amount of committing on IM as you have here @applqpak LOL

**Comment by applqpak** [comment]
Lol, I should. I just don't know where to start.. I feel like a little kid floating around trying to help a bunch of adults :|

**Comment by k3ithos** [comment]
@applqpak well, maybe start off with fixing the bugs

**Comment by applqpak** [comment]
Yeah. I'll probably do the sideline stuff, liek coding the app etc..

**Comment by applqpak** [comment]
Like*
