### ISSUE TITLE
How does this APP work?

### ISSUE THREAD

**Issue by legoboy0215** [LegoCraftPE/iOS_LCPE-App#2]

**Comment by applqpak** [comment]
Easy. I'm creating a Provision Profile for our app, basically an app structure that installs the app on the iDevice and lets the user access the app.

**Comment by k3ithos** [comment]
No, like what is the point of this LOL

**Comment by Vaults1** [comment]
Are we planning to do an android app as well?

**Comment by applqpak** [comment]
I would, but I can't say I'm super familiar with Java and Android SDK :/

**Comment by Vaivez66** [comment]
iOS?

**Comment by Vaults1** [comment]
This is iOS...

**Comment by Vaivez66** [comment]
Android?

**Comment by Vaults1** [comment]
What?

**Comment by Vaults1** [comment]
@applqpak You can code a website for it, and I can make an app which will display the website.

**Comment by applqpak** [comment]
On Android?

**Comment by Vaults1** [comment]
Yes

**Comment by k3ithos** [comment]
But what's the point of this app? What does it do?

**Comment by Vaults1** [comment]
I have no idea...

**Comment by Vaults1** [comment]
Sooo. .. What will this app do??

**Comment by k3ithos** [comment]
<p style="color: red"> <i> No comment provided. </i> </p>

**Comment by Vaults1** [comment]
_No logic found._

**Comment by lavender-sys** [comment]
Umm... _No app found_??

**Comment by legoboy0215** [comment]
lol
